language: php
php:
  - 5.4
before_script:
  - curl -s https://getcomposer.org/installer | php -- --quiet
  - php composer.phar install
script:
  - bin/phpunit
  - bin/phpcs --report="full" --standard="PSR2" src/
  - bin/phpcpd --verbose src/
notifications:
  email:
      - mail@ftrrtf.com
